### ISSUE TITLE
a bunch of NullReferenceException while in editor

### ISSUE THREAD

**Issue by LouisCyfer** [KSPSnark/IndicatorLights#1]
here is what i get when im in editor and it seems it cant set a color right (or something?)
the game runs smooth tho, no crashes cuz of it

here's the error code:
`8935.116: NullReferenceException
          at UnityEngine.Material.SetColor (Int32 nameID, Color color)
          at IndicatorLights.ModuleControllableEmissive.set_Color (Color value)
          at IndicatorLights.ModuleEmissiveController.Update ()
`

i hope it gets fixed soon .. (not complaining tho, just reporting :D)
awesome work so far, LOVE the batteries lights and crew lights on stock parts!

EDIT: clue/hint -> must have to do with the docking ports .. have no sci-tech attached

**Comment by KSPSnark** [comment]
Thanks for the heads-up!

I found one potential spot where the problem may be occurring (not sure that I got it, but this could be it).  I just released v0.10.1, with the fix in.  Can you try with that, and see whether you're still getting the NRE errors?

Incidentally:  the error you mention is in ModuleControllableEmissive, which is a common module present on _all_ indicator lights in my mod.  So it's nothing to do specifically with docking ports-- that is, if you're seeing the problem with docking ports, you could see the problem with any of the indicator lights in the mod.

**Comment by LouisCyfer** [comment]
ahh okies, going to update and check, then reporting back asap
ty for the fix in advance, this mod is one of them must-have's for rounding up KSP at all :)

EDIT:
i believe its gone, the change from `return null;` to `return NO_MATERIALS;` did the deal.
I didn't test that out of VAB yet.

EDIT 2:
yes i think its gone .. YAY!
