### ISSUE TITLE
Re-add (Stock) "HG-5 High Gain Antenna"

### ISSUE THREAD

**Issue by minchinweb** [KSPSnark/IndicatorLights#17]
It seems at some point, the original HG-5 part was replaced by a new model with the same name. Could you re-add this antenna?

If it's helpful, the new part name is `HighGainAntenna5_v2`.

P.S. Thanks for this awesome mod, and thanks for keeping it up to date!

**Comment by KSPSnark** [comment]
Fixed with IndicatorLights release 1.8.2.  Thanks for reporting!
