### ISSUE TITLE
No crew indicator on stock Mk-1 Inline Cockpit

### ISSUE THREAD

**Issue by Beetlecat** [KSPSnark/IndicatorLights#6]
I can't find it in the Indicator Lights configs.

Digging into Squad's configs, there's a mk1InlineCockpit.cfg that has a part name of "Mark2Cockpit." Not to be confused with the *actual* mk2 standard/inline.

Apologies if I'm overlooking something.

**Comment by KSPSnark** [comment]
Nope, this genuinely had no indicator on it; I simply never got around to adding an indicator to this part.

I've now released IndicatorLights 1.4.1, which adds an indicator to the Mk1 inline cockpit.  Thanks!  :-)
